BUCKET_NAME = 'wagon-817-project-sports'
STORAGE_LOCATION = 'models/recommender'
MODEL_FILE_NAME = 'model_cosine_sim.npz'
EVENTS_FILE_NAME = 'events_df.csv'
AHOY_EVENTS_FILE_NAME = 'ahoy_events_df.csv'
USERS_FILE_NAME = 'users_df.csv'
